[default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.default]
optimizer = true
optimizer_runs = 10000
evm_version = 'london'
solc_version = '0.8.19'

[dependencies]
forge-std = { git = 'https://github.com/foundry-rs/forge-std.git', tag = 'master' }
