[default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.default]
optimizer = true
optimizer_runs = 10000
evm_version = 'london'
solc_version = '0.8.19'

[dependencies]
forge-std = { git = 'https://github.com/foundry-rs/forge-std.git', tag = 'v1.14.0' }
openzeppelin-contracts = { git = 'https://github.com/OpenZeppelin/openzeppelin-contracts.git', tag = 'v5.5.0' }

[remappings]
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"forge-std/" = "lib/forge-std/src/"
