[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = 'shanghai'
solc_version = '0.8.20'
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@chainward/core/=src/core/",
    "@chainward/registries/=src/registries/",
    "@chainward/governance/=src/governance/",
    "@chainward/economics/=src/economics/",
    "@chainward/security/=src/security/",
    "@chainward/response/=src/response/",
    "@chainward/types/=src/types/",
    "@chainward/interfaces/=src/interfaces/"
]
